version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ws
    versions:
    - 7.4.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
  - dependency-name: nodemailer
    versions:
    - 6.4.17
  - dependency-name: mocha
    versions:
    - 8.2.1
  - dependency-name: p-queue
    versions:
    - 6.6.2
  - dependency-name: bl
    versions:
    - 4.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
